module.exports  = {
	charlie1: "Charlie \"Megamind\" He is a hulking 6 ft monster who loves getting his pecs touched and coconut water",
	charlie2: "dominating the world with his forehead",
	brendan1: "Brendan \"Degenerate\" Lin towers at 3 ft, commonly seen yelling monkey noises while slapping the bois' butts",
	brendan2: "yelling at his dogshit laptop for \"bad\" League teammates",
	bradley1: "Bradley \"College changed him\" Liu is an Asian e-boy who buys fake Supreme and has a crippling addiction to the \"DEFEAT\" screen in LoL",
	bradley2: "eating his 10th meal of the day while fixing his middle part",
	nikhil1: "Nikhil \"Free poke guy\" Kulkarni is the whitest Indian to exist but still retains his brown side as a stick",
	nikhil2: "going to speech and debate for no reason",
	calvin1: "Calvin \"S&D is for intellectuals\" Xie is infamous for his internship at A VENTURE CAPITALIST FIRM and drinking too much coffee",
	calvin2: "ditching class",
	frank1: "Frank \"Junchu Yan\" Yan is a Chinese immigrant who frequently yells derogatory slurs when playing the dead game Hearthstone.",
	frank2: "在跑 from the ICE",
	evan1: "Evan \"No memes in general\" Ji impressively runs it down at every video game and is adamant against sucking a dick for a million buckaroos.",
	evan2: "simping for Allison, Erica, and Soapy",
	thomas1: "Thomas \“Big PeePee Man\” Yang is a world-class contemporary artist, known for his demonic, borderline illegal drawings/memes and cannot resist saying \“poopcock\” every 10 seconds. ",
	thomas2: "trying to find another asian in Indiana",
	eric1: "Eric \“Teemo is so hot\” Yin is an e-boy furry who is perma S+ tier weird and nearly perma-d from the server for his AIDS-inducing jokes",
	eric2: "playing TFT while complaining about too much work"
};